destination: ../documenting-rest-apis-pdf
url: "http://127.0.0.1:4003"
baseurl: "/docapis"
port: 4003
print: true
print_title: Documenting REST APIs
print_subtitle: version 2.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true


markdown: redcarpet
print: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
exclude:
  - _drafts
  - .idea
  - _site
  - _posts
  - pages/


# this enables collections
collections:
  restapicourse:
    output: true
  publishingapidocs:
    output: true
  voiceovertechniques:
    output: true

# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "restapicourse"
    values:
      layout: "page_print"
      comments: true
      search: true

sass:
    sass_dir: _sass

